---

- name: include OS specific varibles
  include_vars: "{{ ansible_os_family | default('RedHat') }}.yml"
  tags: shorewall

- include: shorewall.yml
  when: shorewall == True
  tags: shorewall

- include: shorewall6.yml
  when: shorewall6 == True
  tags: [ 'shorewall', 'shorewall6' ]
