---

- name: install shorewall6
  action: "{{ansible_pkg_mgr}} name=shorewall6 state=present"
  tags: [ 'shorewall', 'shorewall6' ]

- name: install defaultfile for shorewall6
  template:
    dest: "{{ shorewall6_defaultfile }}"
    src: default/shorewall6.j2
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall6
  tags: [ 'shorewall', 'shorewall6' ]

- name: shorewall6 configuration files
  template:
    dest: "/etc/shorewall6/{{ item }}"
    src: "shorewall6/{{ item }}.j2"
    owner: root
    group: root
    mode: 0640
  with_items:
    - shorewall6.conf
    - params
    - interfaces
    - masq
    - zones
    - policy
    - rules
    - hosts
  notify: restart shorewall6
  tags: [ 'shorewall', 'shorewall6' ]

- name: Create rules.d shorewall6 directory
  file:
    dest: "/etc/shorewall6/rules.d"
    state: directory
    mode: 0750
    owner: root
    group: root
  when: shorewall6_custom_rules is defined
  tags: [ 'shorewall', 'shorewall6' ]

- name: Generate Shorewall6 custom rules
  template: src="shorewall6/customrules.j2" dest="/etc/shorewall6/rules.d/{{ item.key }}.rules"
  with_dict: '{{ shorewall6_custom_rules | default({}) }}'
  when: shorewall6_custom_rules is defined
  notify: restart shorewall6
  tags: [ 'shorewall', 'shorewall6' ]

- name: start and enable the shorewall6 service
  service: name=shorewall6 state=started enabled=yes
  tags: [ 'shorewall', 'shorewall6' ]
