---

- name: install shorewall
  action: "{{ansible_pkg_mgr}} name=shorewall state=present"
  tags: shorewall

- name: Default config
  template:
    dest: "{{ shorewall_defaultfile }}"
    src: default/shorewall.j2
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall
  tags: shorewall

- name: shorewall configuration files
  template:
    dest: "/etc/shorewall/{{ item }}"
    src: "shorewall/{{ item }}.j2"
    owner: root
    group: root
    mode: 0640
  with_items:
    - shorewall.conf
    - params
    - interfaces
    - masq
    - zones
    - policy
    - rules
    - hosts
  notify: restart shorewall
  tags: shorewall

- name: Create rules.d directory
  file:
    dest: "/etc/shorewall/rules.d"
    state: directory
    mode: 0750
    owner: root
    group: root
  when: shorewall_custom_rules is defined
  tags: shorewall

- name: Generate Shorewall custom rules
  template: src="shorewall/customrules.j2" dest="/etc/shorewall/rules.d/{{ item.key }}.rules"
  with_dict: '{{ shorewall_custom_rules | default({}) }}'
  notify: restart shorewall
  when: shorewall_custom_rules is defined
  tags: shorewall

- name: start and enable the shorewall service
  service: name=shorewall state=started enabled=yes
  tags: shorewall
